[Service]
UMask=0027
ProtectSystem=strict
ReadWritePaths=/opt/github-runner-cfa
ReadWritePaths=/srv/client-sites/custom-for-all
ReadWritePaths=/srv/client-services/custom-for-all-form
ReadWritePaths=/run/lock
ProtectHome=true
PrivateTmp=true
ProtectControlGroups=true
IPAddressAllow=127.0.0.53/32
IPAddressDeny=127.0.0.0/8
IPAddressDeny=5.161.61.100/32
IPAddressDeny=10.0.0.0/8
IPAddressDeny=172.16.0.0/12
IPAddressDeny=192.168.0.0/16
IPAddressDeny=169.254.0.0/16
